### ISSUE TITLE
BDE style formatter function misbehaves when parameters are function calls

### ISSUE THREAD

**Issue by jbibollet** [philippe-grenet/exordium#44]
Running it on a line such as
```
it->second->onAckMessage(event.status(), event.messageGUID(), event.correlationId());
```
yields the invalid following output
```
    it->second->onAckMessage(event.status(,
                                          event.messageGUID(
                                                        ,
                                                        event.correlationId());
```

**Comment by philippe-grenet** [comment]
You could go ahead and read http://exordium.io and then fix it yourself, but Okay, I'll do that for you. :smile:

**Comment by philippe-grenet** [comment]
Well that is weird, I cannot reproduce it. Could you try again with the latest version?

I used this:

```cpp
```
void foo()
{
    it->second->onAckMessage(event.status(), event.messageGUID(), event.correlationId());
}
```

If I put the cursor anywhere in the argument list of `onAckMessage` except on a parenthesis, it gives me this:

```cpp
void foo()
{
    it->second->onAckMessage(event.status(),
                             event.messageGUID(),
                             event.correlationId());
}
```

It only get confused if you put the cursor on a paren, which is normal.

**Comment by philippe-grenet** [comment]
I have fixed the problem with the cursor being on a parenthesis like `()`. Now it displays an error and does not mess up the formatting. Commit ebae148

**Comment by jbibollet** [comment]
Well that is really odd... I have the latest version (confirmed because the paste buffer is no longer overwritten), and it still fails.
I created a blank .cpp file, opened it, pasted
```
void foo()
{
    it->second->onAckMessage(event.status(), event.messageGUID(), event.correlationId());
}
```
then put the cursor on the first 'e' of 'event' and `ctrl-c a` and I got:
```
void foo()
{
it->second->onAckMessage(event.status(,
                                      event.messageGUID(,
                                                        event.correlationId());
}
```

**Comment by jbibollet** [comment]
:'(
it's `ctrl-c f` I should have been used :-/
Whats the difference between the two ? I have always used `ctrl-c a` for both .h and .cpp, and it always worked perfectly, except for that use case.

**Comment by jbibollet** [comment]
n/m the difference is quite obvious... interesting I never noticed an issue until now tho.. `ctrl-c a` would also fail with something simple like 
```
it->second->onAckMessage(event.status, event.id);
```

**Comment by philippe-grenet** [comment]
C-c a aligns the arguments in a function or method declaration, e.g. the rules about spaces, stars and ampersand.
C-c f aligns parameters in a function call.
Those are different functions because the expected text and the BDE rules are different...
